### ISSUE TITLE
Replace 3e-3 with constant global

### ISSUE THREAD

**Issue by linxin1994** [schleierlab/mmwave-labscriptlib#1]
https://github.com/schleierlab/mmwave-labscriptlib/blob/aeb36bce21aeff9a0995a9dfcad7df76a339cf22/standard_sequence/standard_sequence.py#L126C5-L126C29

Here the aom is turning off earlier than shutter by 3e-3 to avoid leaking light for the time shutter needs to turn on. This turning on time depend on beam size and location but we want to minimize it and be able to adjust it if needed. Can we use a constant variable instead of manually write 3e-3 out?

**Comment by npeard** [comment]
Yes, we should use a variable. But let's discuss the details of how to implement this. I think Sam wanted to characterize all the open/shut times of the shutters... not sure if he still wants to do that...
