### ISSUE TITLE
replace shutter go_high with open

### ISSUE THREAD

**Issue by linxin1994** [schleierlab/mmwave-labscriptlib#2]
https://github.com/schleierlab/mmwave-labscriptlib/blob/aeb36bce21aeff9a0995a9dfcad7df76a339cf22/standard_sequence/standard_sequence.py#L35

We should use shutter open function instead of go_high because there is already a calibration data to indicate the delay between trigger signal and when the shutter finish open/ start to close

**Comment by npeard** [comment]
For simple changes like this, unless you think it requires discussion for some reason, you should just make the change and then explain why you made the change in the commit message.
